### ISSUE TITLE
Using Moebius sometimes causes weird refresh issues

### ISSUE THREAD

**Issue by flewid** [NuSkooler/enigma-bbs#256]
**Description** 
Using Moebius Editor sometimes causes weird refresh issues. Specifically in the Messages menu, then 'list messages' menu. You have to press the arrow keys to have the menu actually show up. Using PabloDraw doesn't cause this to occur. 

**Environment**
On 0.10 Alpha and 0.11 Beta

**Comment by NuSkooler** [comment]
This _might_ now be fixed with #244. Can you verify (the fix is only in `0.0.11-beta` latest)

**Comment by flewid** [comment]
what's the proper procedure to pull latest ?

# pm2 stop enigma
# cp -R enigma-dir /enigma-dir-backup 
# cd enigma-dir 
# git pull origin master
# composer install 
# pm2 start enigma 

?

**Comment by NuSkooler** [comment]
@flewid I'm not sure what composer is. Generally that line would be `npm install` or `yarn`. You can restart enigma after. My flow is usually (after any backups/etc.):
```
cd enigma-bbs
git pull # or git pull origin 0.0.11-beta
yarn
pm2 restart enigma
```

**Comment by flewid** [comment]
Thanks :) Got it done. 

It appears fixed to me now - but I have also switched from MagiTerm to SyncTerm - which may have been the issue to begin with, as I designed the board using MagiTerm and connecting with SyncTerm everything is off by a couple lines -- anyway, long story short, using moebius, and, syncterm everything looks okay now. I will re-open if anything changes.

**Comment by cognitivegears** [comment]
@flewid @NuSkooler I think this should be able to be closed by now? Even if #244 didn't fix it, there have been a number of other changes since then. I'd suggest we close unless this can be reproduced.
